version: "3.8"

services:

  redis:
    image: redis:7
    container_name: hr-redis
    restart: always
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      retries: 5
      start_period: 5s
      timeout: 2s
        
  mysql:
    image: mysql:8.0
    container_name: hr-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: hr_system
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 5s
      retries: 5
      start_period: 10s
      timeout: 2s
  
  migrations:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile.migrations
    depends_on:
      mysql:
        condition: service_healthy

  auth-service:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile.auth-service
    depends_on:
      redis:
        condition: service_healthy
      mysql:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully
    ports:
      - "50051:50051"
  
  employee-service:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile.employee-service
    depends_on:
      redis:
        condition: service_healthy
      mysql:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully
    ports:
      - "50052:50052"

  api-gateway:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile.api-gateway
    depends_on:
      auth-service:
        condition: service_started
      employee-service:
        condition: service_started
    ports:
      - "8081:8081"

volumes:
  db_data:

